### ISSUE TITLE
Mover de Paths absolutos a relativos

### ISSUE THREAD

**Issue by bosogabriel** [clusterai/clusterai_2020#4]
Reemplazar todos los data paths absolutos y hacerlos relativos (propuesta de usar pathlib de Gabriel)

**Comment by mcallara** [comment]
@bosogabriel no te olvides de hacer un rebase to master, porque acabo de hacer el merge de tu pull request.
Mil gracias!!

**Comment by mcallara** [comment]
@bosogabriel fijate que agregué la clase 3 y los datasets pero no corregí el path a los datos.
