### ISSUE TITLE
Armar estructura de carpetas para segmentacion de datasets (divisiones por tipo, tema, fuente)

### ISSUE THREAD

**Issue by martinamoro** [clusterai/clusterai_2020#7]

**Comment by martinamoro** [comment]
Una vez que estén centralizados los data sets arranco con la segmentación

**Comment by mcallara** [comment]
@martinamoro entiendo que esto fue resuelto en #5 por @bosogabriel. Si te parece bien, cerramos este issue.
Gracias!!

**Comment by martinamoro** [comment]
@mcallara creo que este issue Gabriel lo creo para armar más una estructura de subcarpetas para los datasets, por ej: carpeta Bebidas -> ahí va el dataset de vinos, eso es lo que entendí @bosogabriel me confirmas?

**Comment by bosogabriel** [comment]
Estimados, como decis @martinamoro lo cree yo con el proposito de que hagamos alguna segregacion de datasets, ya sea por tipo de datos o por tipo de temas. @mcallara podemos hablarlo el sabado de ultima.

**Comment by mcallara** [comment]
@bosogabriel , ah, perfecto. Mi pregunta fue más que nada para cerrar el issue en el caso que ya estuviera resuelto. 
Concretamente como feedback, me parece que como lo estructuraron ahora está bien porque si ponemos una jerarquía por temas quizás va a quedar muy "anidado" y después tenés que ir a buscar el dataset a la subcarpeta del tema.
Pero eso ya es una opinión y la verdad es que haberlo organizado ya es un gol. Gracias de nuevo!

**Comment by bosogabriel** [comment]
Estimados, debido al enfoque de modulo sobre el uso de los datasets entiendo que este ticket quedaria desestimado al menos como esta
